[tools]
"github:github/smimesign" = { version = "latest", os = ["macos", "windows"] }
cosign = "latest"
delta = "latest"
jq = "latest"
pipx = "latest"
ripgrep = "latest"
usage = "latest"
uv = "latest"
"pipx:pipenv" = "latest"

[env]
GEM_HOME = "{{ env.HOME }}/.gem"
GOPATH = "{{ env.HOME }}/code/go"
HOSTFILE = "{{ xdg_config_home }}/hosts"
LANG = "en_US.UTF-8"
LC_ALL = "{{ env.LANG }}"
LC_CTYPE = "{{ env.LANG }}"
TZ = "America/New_York"

[settings]
experimental = true
lockfile = true
